### PR TITLE
Fix SC* expansion files not caching on none windows.

### LINKED ISSUE #734: [TD] Linux Covert Ops undefined Tile
Followup on:
[TD] Addon mixfile loading fails on non-Windows OSes #730 

I can only reproduce this on Linux, not on Windows.

In the Covert Ops mission "infiltrated" there is an undefined tile. When the map is explored it will not display correctly. When the radar is active it will also crash the game quickly after it becomes visible. See attached image.

linux-infitrated-undefined-tile

The insert on the bottom right of the image is what the tile looks like in Windows.

### PR DESCRIPTION
**Pull request by OmniBlade**
Fixes any mod or expansion that relied on cached resources.
Fixes #734

### CODE REVIEW

**Comment by hazelnot** [comment]
Checked it out in-game. Game doesn't crash anymore, and the tile gets rendered!

File: common/file.cpp [hunk 1]
```diff
@@ -12,8 +12,8 @@ static void Resolve_File_Single(char* fname)
         return;
     }
 
-    if (ffblk->FindFirst(fname) && strlen(fname) == strlen(ffblk->GetName())) {
-        strncpy(fname, ffblk->GetName(), strlen(fname) + 1);
+    if (ffblk->FindFirst(fname) && strlen(fname) == strlen(ffblk->GetFullName())) {
+        strncpy(fname, ffblk->GetFullName(), strlen(fname) + 1);
```
Comment (giulianobelinassi) [inline common/file.cpp]: Store the value of `strlen` into a variable to avoid recomputing its value.

File: common/file_win.cpp [hunk 2]
```diff
@@ -10,6 +10,11 @@ class Find_File_Data_Win : public Find_File_Data
     virtual ~Find_File_Data_Win();
 
     virtual const char* GetName() const;
+    virtual const char* GetFullName() const
```
Comment (giulianobelinassi) [inline common/file_win.cpp]: Why don't implement this method as returning `nullptr` on the base class, and only implement it on Linux? That way we do not have to provide an implementation always returning `nullptr` for Windows.

**Review by giulianobelinassi — CHANGES_REQUESTED** [review]

**Review by giulianobelinassi — APPROVED** [review]
