### PR TITLE
Fix template expansion explosion in MixFileClass

### LINKED ISSUE #777: MixFileClass: RAM usage explosion on template expansion
The MixFileClass uses templates and its size explodes when expanding. Calculated to be more than 512k, which is a problem on embedded systems.

### PR DESCRIPTION
**Pull request by giulianobelinassi**
Previously, MixFileClass were declared in mixfile.h, which is included
in many .cpp files causing it to be expanded over and over again. This
commit fixes this problem by declaring its functions in the .cpp file
and exporting a MixFileClass<CCFileClass> instance.

Closes #777 

Signed-off-by: Giuliano Belinassi <gbelinassi@suse.de>

### CODE REVIEW

File: common/mixfile.h [hunk 1]
```diff
@@ -161,655 +161,4 @@ template <class T, class TCRC = CRCEngine> class MixFileClass : public Node<MixF
     static List<MixFileClass<T, TCRC>> MixList;
 };
 
-/*
-**	This is the pointer to the first mixfile in the list of mixfiles registered
-**	with the mixfile system.
-*/
-template <class T, class TCRC> List<MixFileClass<T, TCRC>> MixFileClass<T, TCRC>::MixList;
```
Comment (OmniBlade) [inline common/mixfile.h:168]: You should only really need to remove this line to prevent this static member being instantiated in all compilation units. Moving the functions shouldn't be neccesary, at worst maybe they need labling as inline to get them to link just the one instance of the function, but that should be how they are treated by default according to the C++ standards.

**Review by OmniBlade — CHANGES_REQUESTED** [review]
Moving all the functions into a separate header seems overkill and shouldn't be required as far as the standard says.

**Review by OmniBlade — APPROVED** [review]
