### PR TITLE
Fix several memory issues pointer by AddressSanitizer

### LINKED ISSUE #605: class Buffer contains defined behaviour (using delete[] against a void pointer)
Running Vanilla Conquer with TD has highlighted memory warnings upon start-up

image

This is because BufferPtr is declared as a void*, and  doing a delete[] on a void* is undefined in C++

https://discord.com/channels/409121752921276426/770995500677333002/814040181668577280

A simple helper program demonstrates this

int main ()
{
    void *buf;
    buf = new char[4096];
    delete[] buf;
    return 0;
}
main.cc:7:11: warning: deleting ‘void*’ is undefined [-Wdelete-incomplete]
    7 |  delete[] buf;
      |           ^~~
and also reproduces the valgrind warning
==114685== Mismatched free() / delete / delete []
==114685==    at 0x483CFBF: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==114685==    by 0x109193: main (in /home/terrorcide/main)
==114685==  Address 0x4dbcc80 is 0 bytes inside a block of size 4,096 alloc'd
==114685==    at 0x483C583: operator new[](unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==114685==    by 0x10917E: main (in /home/terrorcide/main)

### PR DESCRIPTION
**Pull request by giulianobelinassi**
These commits fix several memory issues pointed by AddressSanitizer. 

closes #605

### CODE REVIEW

File: tiberiandawn/techno.cpp [hunk 1]
```diff
@@ -3912,7 +3912,7 @@ void TechnoClass::Base_Is_Attacked(TechnoClass const* enemy)
                         defender[lp] = (FootClass*)infantry;
                         continue;
                     }
-                    if (value[count] < newweakest) {
+                    if (value[lp] < newweakest) {
```
Comment (hifi) [inline tiberiandawn/techno.cpp]: I wonder if these changes cause a gameplay change? If the original code was buggy and it has always been is it possible fixing this would cause surprising changes?

Comment (giulianobelinassi) [reply tiberiandawn/techno.cpp]: Looking more carefully, I can not convince myself that this indeed fixes the issue. Please disregard it for now.

Comment (giulianobelinassi) [reply tiberiandawn/techno.cpp]: It does fix the problem because count can not be greater than 6.OK.

Looking at the addresses, value[6] == defender[-1], and the value is a pointer to the stack frame which when casted to integer, gives a huge integer and the condition is always false. Therefore just checking for `count < 6 && value[count] < newweakest` should keep the same behavior while not reading memory outside of the array boundary,

**Comment by giulianobelinassi** [comment]
Done. Added a few more commits fixing other memory problems. This commit PR allied with #651 #653 and #654 fixes all  Asan/Lsan issues I found in TD.

With mitigation from #648, TD game runs stable with Asan enabled.

File: common/load.cpp [hunk 2]
```diff
@@ -166,7 +166,7 @@ void* Load_Alloc_Data(const FileClass& file)
     void* ptr = 0;
     long size = const_cast<FileClass&>(file).Size();
 
-    ptr = new char[size];
+    ptr = malloc(size);
```
Comment (hifi) [inline common/load.cpp:169]: I'm not an expert on C++ but does this inhibit correct free behavior as well as the correct free would've been `delete` before and now it would need to be `free()`?

Comment (giulianobelinassi) [reply common/load.cpp:169]: Memory allocated by `Load_Alloc_Data` is currently being released using `free`. Therefore, either the release must be changed to `delete` and several other files has to be changed, or this function can simply alloc memory using `malloc`.

Comment (giulianobelinassi) [reply common/load.cpp:169]: Address Sanitizer catches `delete` of pointers allocated by `malloc`, so it would show up during tests if that broke something.

File: tiberiandawn/radar.cpp [hunk 3]
```diff
@@ -514,7 +514,6 @@ void RadarClass::Render_Terrain(CELL cell, int x, int y, int size)
     ** are terrain type.
     */
     for (lp = 0; lp < 3; lp++) {
-        obj = Map[cell].Overlapper[lp];
```
Comment (giulianobelinassi) [inline tiberiandawn/radar.cpp]: That is why I am not able to reproduce the issue anymore. I accidentally deleted this line.

Comment (giulianobelinassi) [reply tiberiandawn/radar.cpp]: Fixed.

**Review by OmniBlade — APPROVED** [review]
