### PR TITLE
Greatly reduces the CPU use of the game.

### LINKED ISSUE #60: Crash when starting Nod campaign after leaving GDI one.
Standalone build seems to crash if you exit the GDI campaign back to main menu and then try and start the Nod campaign.

### LINKED ISSUE #91: High CPU usage.
Both games at least standalone consume close to 100% of a CPU core at pretty much all times by refreshing menus as fast as possible and by busy waiting between logic ticks. Needs some judicious use of at least `Sleep(1)` or equivalents to force the game to give up its time slice for most menu loops in the game and `Sync_Delay()`.

### LINKED ISSUE #119: Sound crash after playing around with TD mission startups
Glad I run both games in a debugger all the time. I got a somewhat useful backtrace. This is with August 12th hotfix on top of vanilla:

```
Unhandled exception: page fault on read access to 0x06f200a4 in 32-bit code (0xf7c568f6).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:006b GS:0063
 EIP:f7c568f6 ESP:0244f488 EBP:0244f4a8 EFLAGS:00210202(  R- --  I   - - - )
 EAX:06f200a4 EBX:030ee048 ECX:00000002 EDX:0244f536
 ESI:0057422e EDI:0057422a
Stack dump:
0x0244f488:  030ee048 7f3a220f 0244f536 06f200a4
0x0244f498:  00000002 7bca0026 0266f634 0244f4c0
0x0244f4a8:  0244f4f8 004304c3 0266f634 003f8000
0x0244f4b8:  0244f4c8 004304c3 0244f536 06f200a4
0x0244f4c8:  00000002 c0000001 0244f4f0 0244f550
0x0244f4d8:  0244f538 7f2e78a0 0244f500 00004216
Backtrace:
=>0 0xf7c568f6 (0x0244f4a8)
  1 0x004304c3 _Z11Simple_CopyPPvPiS0_S1_S0_i+0x8a(source=0x5741c9, ssize=0x5741cd, alternate=0x57422a, altsize=0x57422e, dest=0x244f52c, size=0x2) [\\?\unix\home\hifi\work\Vanilla-Conquer\common\soundio.cpp:1481] in vanillatd (0x0244f4f8)
  2 0x0042e82c _Z11Sample_CopyP17SampleTrackerTypePPvPiS2_S3_S1_i13SCompressTypeS1_Ps+0xa7(st=0x574197, source=0x5741c9, ssize=0x5741cd, alternate=0x57422a, altsize=0x57422e, dest=0x30ee048, size=0x2000, scomp=SCOMP_SOS, trailer=0x5741fd, trailersize=0x5741fb) [\\?\unix\home\hifi\work\Vanilla-Conquer\common\soundio.cpp:1531] in vanillatd (0x0244f548)
  3 0x00446afe _Z20Maintenance_Callbackv+0x1e9() [\\?\unix\home\hifi\work\Vanilla-Conquer\common\soundio.cpp:149] in vanillatd (0x0244f5d8)
  4 0x004476f2 _Z20Sound_Timer_Callbackjjmmm@20+0x29(uID=0, uMsg=0, dwUser=0, dw1=0, dw2=0) [\\?\unix\home\hifi\work\Vanilla-Conquer\common\soundio.cpp:648] in vanillatd (0x0244f5f8)
  5 0x004387c8 _Z14Sound_Callbackv+0x5f() [\\?\unix\home\hifi\work\Vanilla-Conquer\common\soundio.cpp:528] in vanillatd (0x0244f638)
  6 0x00496a28 _ZN10ThemeClass2AIEv+0xb7() [\\?\unix\home\hifi\work\Vanilla-Conquer\tiberiandawn\theme.cpp:201] in vanillatd (0x0244f668)
  7 0x0046663e _Z9Call_Backv+0x1d() [\\?\unix\home\hifi\work\Vanilla-Conquer\tiberiandawn\conquer.cpp:1113] in vanillatd (0x0244f708)
  8 0x0043a504 _Z15Fade_Palette_ToPvjPFvvE+0xa7(palette1=0x2550940, delay=0xf, callback=0x466620) [\\?\unix\home\hifi\work\Vanilla-Conquer\common\palette.cpp:187] in vanillatd (0x0244f738)
  9 0x00430118 _Z11Select_Gameb+0x1667(fade=0x1) [\\?\unix\home\hifi\work\Vanilla-Conquer\tiberiandawn\init.cpp:1529] in vanillatd (0x0244fa58)
  10 0x00468f06 _Z9Main_GameiPPc+0x41(argc=0x2, argv=0x244fdd8) [\\?\unix\home\hifi\work\Vanilla-Conquer\tiberiandawn\conquer.cpp:152] in vanillatd (0x0244fb28)
  11 0x00427e7d WinMain@16+0xc9c(instance=0x400000, command_line="-CD.", command_show=0xa) [\\?\unix\home\hifi\work\Vanilla-Conquer\tiberiandawn\startup.cpp:577] in vanillatd (0x0244fe68)
  12 0x0052174d strtrim+0x304(str="ï Uï∞] %ädK{ÉÉÉÉÉÉÉÉï Uï∞] %êdK{ÉÉÉÉÉÉÉÉï Uï∞] %îdK{ÉÉÉÉÉÉÉÉï Uï∞] %ÉdK{ÉÉÉÉÉÉÉÉï Uï∞] %ödK{ÉÉÉÉÉÉÉÉï Uï∞] %ÿdK{ÉÉÉÉÉÉÉÉï Uï∞] %£dK{ÉÉÉÉÉÉÉÉï Uï∞] %ádK{ÉÉÉÉÉÉÉÉï Uï∞] %ñdK{ÉÉÉÉÉÉÉÉï Uï∞] %¿dK{ÉÉÉÉÉÉÉÉï Uï∞] %¼dK{ÉÉÉÉÉÉÉÉ
ï Uï∞] %░dK{ÉÉÉÉÉÉÉÉï Uï∞] %░dK{ÉÉÉÉÉÉÉÉï Uï∞] %┤dK{ÉÉÉÉÉÉÉÉï Uï∞] %┤dK{ÉÉÉÉÉÉÉÉï Uï∞] %╕dK{ÉÉÉÉÉÉÉÉï Uï∞] %╝dK{ÉÉÉÉÉÉÉÉï Uï∞] %└dK{ÉÉÉÉÉÉÉÉï Uï∞] %─dK{ÉÉÉÉÉÉÉÉï Uï∞] %╚dK{ÉÉÉÉÉÉÉÉï Uï∞] %╠dK{ÉÉÉÉÉÉÉÉï Uï∞] %╨dK{ÉÉÉÉÉÉÉÉï Uï∞] %╘dK{ÉÉÉÉÉÉÉÉï Uï∞] %╪dK{ÉÉÉ
ÉÉÉÉÉï Uï∞] %▄dK{ÉÉÉÉÉÉÉÉï Uï∞] %αdK{ÉÉÉÉÉÉÉÉï Uï∞] %ΣdK{ÉÉÉÉÉÉÉÉï Uï∞] %ΦdK{ÉÉÉÉÉÉÉÉï Uï∞] %∞dK{ÉÉÉÉÉÉÉÉï Uï∞] %≡dK{ÉÉÉÉÉÉÉÉï Uï∞] %⌠dK{ÉÉÉÉÉÉÉÉï Uï∞] %°dK{ÉÉÉÉÉÉÉÉï Uï∞] %ⁿdK{ÉÉÉÉÉÉÉÉï Uï∞] %") [\\?\unix\home\hifi\work\Vanilla-Conquer\common\misc.c:167] in vanillatd (0x0244fe88)
  13 0x00401386 _Z5UnionRK4RectS1_+0x401385(rect1=0x7b454882, rect2=0x3ff000) [\\?\unix\home\hifi\work\Vanilla-Conquer\common\rect.cpp:197] in vanillatd (0x0244ff28)
  14 0x7b454882 in kernel32 (+0x34881) (0x0244ff48)
  15 0x7b454cfc in kernel32 (+0x34cfb) (0x0244ffd8)
  16 0x7b45488e in kernel32 (+0x3488d) (0x0244ffec)
0xf7c568f6: movzbl      0x0(%eax),%ebx
```

I first started the GDI mission, played a few seconds, abort, NOD mission, few seconds, abort, GDI mission, boom before the first rendered map frame.

### PR DESCRIPTION
**Pull request by OmniBlade**
Adds a liberal sprinkling of sleep across the games many busy wait loops.

Subject to testing it fixes the following bugs:
Fixes #60 
Fixes #91 
Fixes #119 

The fixes to the mysterious sound crash are probably due to the new delays masking whatever race condition led to it.

Also fixes the scroll rate being far too fast without needing interventions from a ddraw.dll.

### CODE REVIEW

File: redalert/conquer.cpp [hunk 1]
```diff
@@ -2093,6 +2095,8 @@ static void Sync_Delay(void)
             }
             Map.Render();
         }
+
+        std::this_thread::sleep_for(std::chrono::milliseconds(1));
```
Comment (ghost) [inline redalert/conquer.cpp]: Not sure if you wanna add mutex here for `FrameTimer`. (Check body of loop above)

Then you would need to remember:
```
while (true) {
  {
  // here set mutex
  // and do stuff
  }
  // here sleep
}

```

**Comment by OmniBlade** [comment]
Looks like we might need https://github.com/meganz/mingw-std-threads or to select a different version of mingw on the CI.

File: redalert/conquer.cpp (hunk 1 above)
Comment (OmniBlade) [reply redalert/conquer.cpp]: Not sure what the concern is that might need a mutex, some potential race condition I'm not seeing?

Comment (ghost) [reply redalert/conquer.cpp]: I'm kinda not sure about global instance `FrameTimer`, if it's used by more than one thread.

**Comment by hifi** [comment]
Shouldn't we instead of adding random sleeps around the engine add a function call to a proper frame limiter?

File: redalert/conquer.cpp (hunk 1 above)
Comment (hifi) [reply redalert/conquer.cpp]: The game doesn't really do threading that much. There's that winmm timer callback thing for sound and mouse code but other than that it runs single threaded. @OmniBlade said this is probably a remnant of how the DOS code used interrupts to trigger the updates.

It would be great if we could completely remove those and make this run single threaded in the long run as it will also simplify and remove those possible race conditions.

**Comment by OmniBlade** [comment]
Well they are added where an eventual flip/draw call will need to be made when ported to a graphics api that doesn't pretend you have direct access to the frame buffer anymore, so I'd say more fine grained frame limiting should be implemented with that piece of work.

This at least marks most of the points in the game engine where such things will need to be considered for later refactoring and greatly improves the behaviour of the engine on a multitasking OS. Its just a bonus that it seems to fix the sound engine crashes.

I've refactored the PR to use win32 Sleep on windows and Posix nanosleep on none windows for now to avoid the issues with std::thread and mingw.

**Comment by OmniBlade** [comment]
I've updated the PR with an attempt at a frame limiter that should try and keep the refresh rate around 120 fps which should be more than enough. Game runs fine for me with close to 0% CPU use for most situations rather than near 100% on one core.

File: redalert/expand.cpp [hunk 2]
```diff
@@ -157,16 +158,16 @@ const char* XlatNames[] = {"Zusammenstoss",
                            "Harte Verhandlungen",           //	"SCG47EA",		// Negotiations
                            "Ferngelenktes Kriegsspielzeug", //	"SCG45EA",		// Monster Tank Madness
                            "Licht aus",                     //	"SCG44EA",		// Time Flies
-                           "Molekulare Kriegsf�hrung",      //	"SCG48EA",		// Absolut MADness
```
Comment (hifi) [inline redalert/expand.cpp]: Your editor got caught up with these. We should do a PR that converts all of this into escape sequences.

**Review by hifi — CHANGES_REQUESTED** [review]
PR looks good otherwise but the unintentional in-game text changes need to be reverted.

File: redalert/expand.cpp (hunk 2 above)
Comment (OmniBlade) [reply redalert/expand.cpp]: Second time its done that to me and I had to revert it. Fixed now.

**Review by hifi — APPROVED** [review]
